### ISSUE TITLE
顯示添加文章日期的日曆 (hexo-generator-calendar)

### ISSUE THREAD

**Issue by ouoholly** [ouoholly/ouoholly.github.io#2]
看到這篇文章： [给hexo博客的NEXT添加一个云日历 | 会飞的扫帚](https://guogiant.club/2019/06/24/%E7%BB%99hexo%E5%8D%9A%E5%AE%A2%E7%9A%84NEXT%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA%E4%BA%91%E6%97%A5%E5%8E%86/)

但不能直接應用在 butterfly 主題，待研究。

**Comment by ouoholly** [comment]
找到 Butterfly 主題的教學：[Hexo添加小部件(Butterfly主题) | HCLonely Blog](https://blog.hclonely.com/posts/57bd67ce/#%E6%96%87%E7%AB%A0%E6%97%A5%E5%8E%86)

大功告成！

**Comment by zzzzzzzzzoe** [comment]
您好，我刚刚阅读了您的[这篇文章](https://ouoholly.github.io/post/butterfly-add-hexo-generator-calendar/#6-%E5%89%B5%E5%BB%BA-calendar-styl)，给我启发去添加日历插件，可是到了第五步： 修改 Butterfly config 配置，这里无法进行了。因为我在butterfly文件下的_config.yml中没有发现CDN_USE:>js: 这个部分。我猜可能是butterfly版本不同的原因（我的是4.8.5），因为我的技术很菜，想请问您可以如何解决这个问题。再次谢谢您分享这篇文章！

**Comment by ouoholly** [comment]
> @ZoeBezos： 您好，我刚刚阅读了您的[这篇文章](https://ouoholly.github.io/post/butterfly-add-hexo-generator-calendar/#6-%E5%89%B5%E5%BB%BA-calendar-styl)，给我启发去添加日历插件，可是到了第五步： 修改 Butterfly config 配置，这里无法进行了。因为我在butterfly文件下的_config.yml中没有发现CDN_USE:>js: 这个部分。我猜可能是butterfly版本不同的原因（我的是4.8.5），因为我的技术很菜，想请问您可以如何解决这个问题。再次谢谢您分享这篇文章！

https://github.com/jerryc127/hexo-theme-butterfly/blob/dev/_config.yml
可以試試加到 inject 部份的 bottom 下方，即第907行開始加上 
`- <script src="/js/calendar.js"></script>`
`- <script src="/js/languages.js"></script>`
